spring.application.name=fingenie-backend
spring.datasource.url=jdbc:mysql://localhost:3306/fingenie_db
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
 
server.port=8080
 
jwt.secret=fingenie_super_secret_jwt_key_2024
jwt.expiration=86400000
gemini.api.key=YOUR_API_KEY